spring.application.name=Booking-Photo;
# C?u hï¿½nh k?t n?i CSDL

#spring.datasource.url=jdbc:sqlserver://bookingphoto.database.windows.net:1433;database=bookingphoto;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=CloudSA0492ce2a
#spring.datasource.password=tuannhung1210!@!)
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# C?u hình k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://pg-14a72890-danghoaiduc9-bd0e.h.aivencloud.com:12448/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_lF5OKD0V_Rn0hIdUUAi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=80
# Bật CORS cho toàn bộ API

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.signerKey=xJTUVPssT2uOmsKKn7dmwi/ZuUg1b8ECkPuoSBYziE4ldzMBtSNkaftz1U372J/e
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
