spring.application.name=Booking-Photo;
# C?u h�nh k?t n?i CSDL
spring.datasource.url=jdbc:sqlserver://bookingphoto.database.windows.net:1433;database=bookingphoto;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=CloudSA0492ce2a
spring.datasource.password=tuannhung1210!@!)
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# C?u h�nh Hibernate th�ng qua JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port = 80
jwt.signerKey=xJTUVPssT2uOmsKKn7dmwi/ZuUg1b8ECkPuoSBYziE4ldzMBtSNkaftz1U372J/e

