name: Deploy Spring Boot (Gradle) to Azure

on:
  push:
    branches:
      - main # Chạy khi có code mới trên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên máy Linux

    steps:
      - name: Checkout code từ GitHub
        uses: actions/checkout@v3

      - name: Cài đặt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cấp quyền chạy Gradle Wrapper
        working-directory: BE/Booking-Photo
        run: chmod +x gradlew

      - name: Build ứng dụng với Gradle
        working-directory: BE/Booking-Photo
        run: ./gradlew clean bootJar -x test

      - name: Deploy lên Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "bookingphoto" # Tên App Service trên Azure
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: BE/Booking-Photo/build/libs/*.jar
