name: Build and deploy JAR app to Azure Web App - bookingphoto (Gradle)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout code từ GitHub
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cấp quyền chạy Gradle Wrapper
        working-directory: BE/Booking-Photo  # Chạy lệnh trong thư mục này
        run: chmod +x gradlew

      - name: Build ứng dụng với Gradle
        working-directory: BE/Booking-Photo  # Chạy Gradle trong thư mục này
        run: ./gradlew clean bootJar -x test

      - name: Upload artifact để deploy
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'BE/Booking-Photo/build/libs/*.jar'  # Đường dẫn đúng của .jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact từ build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Deploy lên Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bookingphoto'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_916097DD9EDB4DCD91985275AD4CF7FF }}
